/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sql;

import static com.mycompany.sql.SQL.empleados;
import java.sql.SQLException;
import java.util.InputMismatchException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author roroc
 */
public class MenuEmpleados extends javax.swing.JFrame {
public static GestionBBDD gestion;
    /**
     * Creates new form MenuEmpleados
     */
    public MenuEmpleados() {
        initComponents();
                try {
             gestion = new GestionBBDD();
            //gestion.BorrarEnGestionEmpleados(12);
            //gestion.ActualizarEnGestionEmpleados(1, "Vicente", 30, "B", 500);
            gestion.ListarEnGestionEmpleados();
            //System.out.println(empleados);
            
        } catch (SQLException ex) {
            System.err.println("Error a la hora de hacer algo relacionado con los empleados");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jButtonAgrEmpleado = new javax.swing.JButton();
        jButtonEdiEmpleado = new javax.swing.JButton();
        jButtonEliEmpleado = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 204, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 500));

        Titulo.setFont(new java.awt.Font("Yu Gothic Medium", 3, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 51, 255));
        Titulo.setText("Bienvenido al menú para empleados");

        jButtonAgrEmpleado.setText("Agregar Empleado");
        jButtonAgrEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgrEmpleadoActionPerformed(evt);
            }
        });

        jButtonEdiEmpleado.setText("Editar Empleado");
        jButtonEdiEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdiEmpleadoActionPerformed(evt);
            }
        });

        jButtonEliEmpleado.setText("Eliminar Empleado");
        jButtonEliEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliEmpleadoActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEliEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAgrEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEdiEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(Titulo)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAgrEmpleado)
                .addGap(18, 18, 18)
                .addComponent(jButtonEdiEmpleado)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalir)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgrEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgrEmpleadoActionPerformed
        // TODO add your handling code here:
        AgregarEmpleado ag = new AgregarEmpleado(this, true);
        ag.setVisible(true);
    }//GEN-LAST:event_jButtonAgrEmpleadoActionPerformed

    private void jButtonEdiEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdiEmpleadoActionPerformed
            
    try {
        String id = JOptionPane.showInputDialog(this, "Diga el id del empleado a editar \n Empleados actuales: \n " + empleados);
        int idint = Integer.parseInt(id);
        boolean existe = gestion.encontrarEmpleado(idint);
        Empleado empleado = gestion.devolverEmpleado(idint);
        if (existe) {
            EditarEmpleado editar =  new EditarEmpleado(empleado);
            editar.setVisible(true);
        } else{
            JOptionPane.showMessageDialog(this, "El empleado no se puede editar, verifica el id ","",2);
        }
    } catch (SQLException ex) {
        System.err.println(ex.getMessage());
    }
        catch (NumberFormatException in){
        JOptionPane.showMessageDialog(this, "Inserte un NUMERO ","",0);
    }
    }//GEN-LAST:event_jButtonEdiEmpleadoActionPerformed

    private void jButtonEliEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliEmpleadoActionPerformed

    try {
        
        String id = JOptionPane.showInputDialog(this, "Diga el id del empleado a eliminar \n Empleados actuales: \n " + empleados);
        int idint = Integer.parseInt(id);
        boolean existe = gestion.encontrarEmpleado(idint);
        if (existe) {
            gestion.BorrarEnGestionEmpleados(idint);
            empleados.remove(idint);
        } else{
            JOptionPane.showMessageDialog(this, "El empleado no se puede editar, verifica el id ","",2);
        }
    } catch (SQLException ex) {
        System.err.println(ex.getMessage());
    }
    catch (NumberFormatException in){
        JOptionPane.showMessageDialog(this, "Inserte un NUMERO ","",0);
    }
    }//GEN-LAST:event_jButtonEliEmpleadoActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButtonAgr;
    private javax.swing.JButton jButtonAgr1;
    private javax.swing.JButton jButtonAgr2;
    private javax.swing.JButton jButtonAgr3;
    private javax.swing.JButton jButtonAgr4;
    private javax.swing.JButton jButtonAgr5;
    private javax.swing.JButton jButtonAgr6;
    private javax.swing.JButton jButtonAgr7;
    private javax.swing.JButton jButtonAgr8;
    private javax.swing.JButton jButtonAgrEmpleado;
    private javax.swing.JButton jButtonEdiEmpleado;
    private javax.swing.JButton jButtonEliEmpleado;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
